sonar.projectKey=melihdemir0_travel-memory-map
sonar.organization=melihdemir0

sonar.projectName=travel-memory-map
sonar.projectVersion=0.0.0

sonar.sources=src
sonar.sourceEncoding=UTF-8

sonar.tests=src/tests
sonar.test.inclusions=src/tests/**/*.test.js,src/tests/**/*.test.jsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=dist/**,node_modules/**
